### ISSUE TITLE
What about background jobs?

### ISSUE THREAD

**Issue by szepeviktor** [serversideup/docker-php#23]
- scheduled jobs (cron)
- queues

**Comment by jaydrogers** [comment]
Great question! I have a lot of documentation to write yet 😅

Mainly these types of jobs are focused on Laravel. I will work on providing better documentation how to do this in the next release.

### How to run a scheduled job
I adopted a method from what I learned from @paulredmond and created an infinite loop if `TASK_SCHEDULER_CONTAINER == true`.

This is great because it allows the cron to be controlled within the app (rather than having to worry about server configurations).

https://github.com/serversideup/docker-php/blob/f2f6591a55094da51841e38021a3c5b4db3d047a/php/8.0/fpm-nginx/start-container#L40-L51

### Running Queues
I adopted this method from @fideloper, where if I pass an argument to the `start-container` script, it runs that command instead. It's been working great for me with Docker Swarm.

https://github.com/serversideup/docker-php/blob/f2f6591a55094da51841e38021a3c5b4db3d047a/php/8.0/fpm-nginx/start-container#L53-L59

### Moving forward
* I will get these documented in the next release.

**Comment by jaydrogers** [comment]
Documentation how to do this specifically with Laravel has been added to the README 🥳
