### ISSUE TITLE
[Question] Would it be possible to make it all run Alpine rather than Ubuntu?

### ISSUE THREAD

**Issue by jpmurray** [serversideup/docker-php#33]
I must say, I'm a _heavy_ RaspberryPi user myself, and last time I checked, the Ubuntu images did not play well with ARM based system... Is it something that changed lately, multi arch images for ubuntu? If not, is there any reason why you don't use Alpine here?

**Comment by jaydrogers** [comment]
Great question!

I chose Ubuntu just for the sake of simplicity and and community support. Before I started Docker I managed a lot of Ubuntu servers in production, so many of what I had then was translated into what I have now.

Alpine is on my radar for the future, but right now it's not on the immediate horizon.

I'm going to close this issue for now since it is answered, but I greatly appreciate you asking this question.

If you happen to fork this and get it running on Alpine, I'd love to see how you got it working and maybe we can collaborate to merge the changes if you wanted.

Thanks for reaching out!

**Comment by jpmurray** [comment]
Oh I get the feeling ! I'm still a hardcore server manager myself. I've been trying to take up Docker for a while, but it just don't click for me. I get the advantages, but... Yeah, I'm stuck in my old ways ;-)

First thing for me will be running it from Ubuntu first. I mean, if it does run well over ARM now, I don't see why I would reinvent the wheel ! If I ever have to / get to try Alpine, I'll sure be pinging you! In the meantime, I've just stalked you on Twitter for a follow up question 😅

**Comment by jaydrogers** [comment]
Not stalking if I am posting things in public 😁

Thanks for reaching out!
