### ISSUE TITLE
Custom start up script not executing

### ISSUE THREAD

**Issue by rlvillacarlos** [serversideup/docker-php#371]
### Affected Docker Images

`php:8.3-fpm-nginx`

### Current Behavior

Custom script is not executing.

### Expected Behavior

Following the instructions in https://serversideup.net/open-source/docker-php/docs/customizing-the-image/adding-your-own-start-up-scripts#example-create-a-custom-entrypoint-script, the custom script should output the test message in the console.  

![image](https://github.com/serversideup/docker-php/assets/11273158/35f1de23-35d3-4581-8bf8-9ace7e70e081)

### Steps To Reproduce

1. Create a custom shellscript in the entrypoint.d directory
2. Create custom Dockerfile.
3. Use the Dockerfile in a docker-compose file
4. Run docker compose up

**Comment by jaydrogers** [comment]
Your example is missing the parts from "[Additional Steps For FPM-Apache & FPM-NGINX (S6 Overlay based images)](https://serversideup.net/open-source/docker-php/docs/customizing-the-image/adding-your-own-start-up-scripts#additional-steps-for-fpm-apache-fpm-nginx-s6-overlay-based-images)"

Since you're using FPM-NGINX, that's an S6 Overlay image... meaning you need to call `docker-php-serversideup-s6-init` after you copy the scripts over.
