### ISSUE TITLE
Laravel Scheduler/Queue Worker HEALTHCHECK Fails (Docs Bug?)

### ISSUE THREAD

**Issue by tsterker** [serversideup/docker-php#391]
### Steps To Reproduce

- Follow the docs for starting a queue worker: https://serversideup.net/open-source/docker-php/docs/laravel/laravel-queue
- See the container being shown as unhealthy:
```bash
docker ps
docker inspect <container>
```

#### What did you expect?

As per the [docs](https://serversideup.net/open-source/docker-php/docs/laravel/laravel-queue) it is mentioned that we are intentionally re-using the same app image:

> Notice we're using the same my/laravel-app image for both the PHP and Queue services. This is a common practice to keep the image consistent.

So, I would expect that there is either
- (A) A way to disable the stock healthcheck 
- (B) Documentation that we need to disable the health check when not running our app as HTTP service

#### What happened instead?

If followed the docs and got an unhealthy container.

### Affected Docker Images

Tested with `serversideup/php:8.3-unit-v3.2.0`

### Anything else?

# Solution / Workaround

As a quick fix, we can simply disable the healthcheck:

```diff
  task:
    build:
      context: .
    command: ["php", "/var/www/html/artisan", "schedule:work"]
+   healthcheck: { test: ['NONE'] }
    volumes:
      - .:/var/www/html
```

I wonder if there are somewhat clean ways to introduce a dedicated healthcheck that could properly/cleanly determine if the queue worker is healthy.

**Comment by lam0819** [comment]
you save me

**Comment by IgordeOliveira** [comment]
Its happen to me in production, its possible to disable health checks without docker compose ?

**Comment by jaydrogers** [comment]
### The problem
If you're using the same base image of `fpm-nginx` for your web and Laravel Queue (like we do), Laravel Queues do not have a health check to ensure the queue is running (unlike Horizon, which uses [`horizon:status`](https://laravel.com/docs/11.x/horizon#running-horizon)

### The solution
Unfortunately disabling the health check is required.

### More detail
To disable a Docker healthcheck, you can use different approaches in Docker Compose and Dockerfile:

#### Docker Compose:
You can disable the healthcheck by setting it to `null`:

```yaml
services:
  your_service:
    image: your_image
    healthcheck:
      disable: true
```

2. In Dockerfile:

If you've defined a healthcheck in your Dockerfile, you can disable it by using the `HEALTHCHECK NONE` instruction:

```dockerfile
# Disable healthcheck
HEALTHCHECK NONE
```

More detail here: https://docs.docker.com/compose/compose-file/05-services/#healthcheck

### Next steps
- I will leave this issue open so I remember to update the docs on this
- If anyone knows of a definition of truth to ensure the queue is running, I would much rather ensure it is running with a health check instead of disabling it all together

**Comment by jaydrogers** [comment]
Instead of setting the `HEALTHCHECK NONE`, I am thinking of adding native health check scripts, proposed here:

- https://github.com/serversideup/docker-php/issues/444

Please let me know on that other thread if you like where this is going. Hoping to get this done in the next release.
