### ISSUE TITLE
Laravel automations not working when not using .env file

### ISSUE THREAD

**Issue by dakira** [serversideup/docker-php#47]
In certain cloud deployment scenarios, all of the environment is set on the hosting site (e.g. Azure App Service) so that the .env is empty / not needed. The following unfortunately relies on .env existing and being used.

https://github.com/serversideup/docker-php/blob/4233993f7367c3fd39789a5826917bdfd12b4436/templates/fpm/etc/cont-init.d/50-laravel-automations#L11

Optimally the correct precedence should be used (i.e. what phpdotenv also uses). Maybe check if environment variable exists and use it if it does, if not check if .env exists and source it, if it does.

**Comment by jaydrogers** [comment]
I think the true discussion is down to this line: https://github.com/serversideup/docker-php/blob/4233993f7367c3fd39789a5826917bdfd12b4436/templates/fpm/etc/cont-init.d/50-laravel-automations#L14

This line was added when things were more automated.

### Proposed change
* Maybe I just remove condition all together? I don't see a need for it now since we can explicitly enable migrations now with `AUTORUN_LARAVEL_MIGRATION`. Meaning if you have `AUTORUN_LARAVEL_MIGRATION` set to true, it should attempt to run the migrations without checking what APP_ENV you are in.

### Opening up for comment
Does this sound good @dakira? @danpastori: What are your thoughts?

**Comment by shinsenter** [comment]
@jaydrogers 
According to the information [from the official Laravel documentation](https://laravel.com/docs/8.x/configuration#additional-environment-files), Laravel determines if either the APP_ENV environment variable has been externally provided.

> Before loading your application's environment variables, Laravel determines if either the APP_ENV environment variable has been externally provided or if the --env CLI argument has been specified. If so, Laravel will attempt to load an .env.[APP_ENV] file if it exists. If it does not exist, the default .env file will be loaded.

I think it's better for letting user change the value of `APP_ENV` either from `docker-compose.yml` file or via the docker command. The default value should be set as `APP_ENV_SETTING=${APP_ENV:-production}`.

**Comment by jaydrogers** [comment]
For sure, I totally agree with this.

My proposal is I think I can eliminate this line all together: https://github.com/serversideup/docker-php/blob/4233993f7367c3fd39789a5826917bdfd12b4436/templates/fpm/etc/cont-init.d/50-laravel-automations#L14

I don't think we need to check for any of this anymore. Thoughts?

**Comment by shinsenter** [comment]
@jaydrogers 
Yes, I think you can remove that condition.

By the way, in the `AUTORUN_LARAVEL_REFRESH_CACHE` block, it should be only these two commands:
```
su - webuser -c "php $WEBUSER_HOME/artisan optimize:clear"
su - webuser -c "php $WEBUSER_HOME/artisan optimize"
```

Ref:
- https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Console/OptimizeClearCommand.php
- https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Console/OptimizeCommand.php

**Comment by jaydrogers** [comment]
### Example of new automation script
Here's the example that I am thinking of updating it to, what does everyone think? https://github.com/serversideup/docker-php/blob/fix/adjust-automation-logic/templates/fpm/etc/cont-init.d/50-laravel-automations

### AUTORUN_LARAVEL_REFRESH_CACHE
We had issues with this in the past, that's why I commented it out. I might want to circle back with @danpastori to see if it is safe to renable it. That might be done on another PR/issue though.

Let me know your thoughts on the script! 😃👍

**Comment by shinsenter** [comment]
@jaydrogers 
Since some migration operations are destructive, which means they may cause us to lose data.
Honestly, I think `--force` flag is not a good idea for production.

```bash 
su - webuser -c "php $WEBUSER_HOME/artisan migrate --force"
```

**Comment by jaydrogers** [comment]
> I think --force flag is not a good idea for production

If we don't add `--force`, won't it prompt for a confirmation? Since there is no TTY, I think we need to leave it this way, correct?

Also, the user is **choosing** to enable this migration too... so it's not it's enabled by default.

Looking forward to hearing your thoughts!

**Comment by shinsenter** [comment]
I think `${AUTORUN_LARAVEL_MIGRATION:="false"}` may be a good choice for now, and it should be set to `false` for production.

I tried to imagine the case that I needed to run multiple instances behind a LB for production, it would be a big deal.

**Comment by jaydrogers** [comment]
I totally agree.

The migration script is great for small apps, but for large apps we recommend running all migrations manually. 👍

**Comment by shinsenter** [comment]
So, the PR is LGTM

**Comment by jaydrogers** [comment]
Just merged this fix 🎉🚀

**Comment by dakira** [comment]
@jaydrogers @shinsenter Hey. Sorry for not being part of the discussion, was busy with my family. Thanks for fixing this! :-)
